### PR TITLE
Support playwright

### PR DESCRIPTION
**Pull request by dcrowe**
Integration with Microsoft's Playwright

Issue: https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/129

### CODE REVIEW

**Comment by dcrowe** [comment]
Tests still coming

**Comment by dcrowe** [comment]
Tests done now. This PR only covers the synchronous API. I'll do the async work later.

**Comment by dcrowe** [comment]
Note, code coverage results are affected by: https://github.com/microsoft/playwright-python/issues/313

**Comment by dcrowe** [comment]
I've added async support now.

**Comment by dcrowe** [comment]
@pashidlos I think its finally ready for review

**Comment by pashidlos** [comment]
I'm on it!

**Comment by pashidlos** [comment]
not sure if I'm doing it right 
but I'm getting error 
```python
Traceback (most recent call last):
  File "example_playwright.py", line 25, in <module>
    vrt.trackPage(page, 'Home page')
  File "/Users/pashidlos/work/vrt/sdk-python/visual_regression_tracker/playwright.py", line 75, in trackPage
    self.track(TestRun(
  File "/Users/pashidlos/work/vrt/sdk-python/visual_regression_tracker/visualRegressionTracker.py", line 92, in track
    result = self._submitTestResult(test)
  File "/Users/pashidlos/work/vrt/sdk-python/visual_regression_tracker/visualRegressionTracker.py", line 80, in _submitTestResult
    result = _http_request(
  File "/Users/pashidlos/work/vrt/sdk-python/visual_regression_tracker/visualRegressionTracker.py", line 111, in _http_request
    response = request(url, json=data, headers=headers)
  File "/Users/pashidlos/.conda/envs/sdk-python/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/pashidlos/.conda/envs/sdk-python/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/pashidlos/.conda/envs/sdk-python/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/Users/pashidlos/.conda/envs/sdk-python/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/Users/pashidlos/.conda/envs/sdk-python/lib/python3.8/site-packages/requests/models.py", line 317, in prepare
    self.prepare_body(data, files, json)
  File "/Users/pashidlos/.conda/envs/sdk-python/lib/python3.8/site-packages/requests/models.py", line 467, in prepare_body
    body = complexjson.dumps(json)
  File "/Users/pashidlos/.conda/envs/sdk-python/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/pashidlos/.conda/envs/sdk-python/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/pashidlos/.conda/envs/sdk-python/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/pashidlos/.conda/envs/sdk-python/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

```

the code I'm executing
```python
from playwright import sync_playwright
from visual_regression_tracker import Config, TestRun
from visual_regression_tracker.playwright import PlaywrightVisualRegressionTracker

config = Config(
    apiUrl='http://localhost:4200',
    project='Default project',
    apiKey='0TK0P0NQP6MNFQQPTYYBN27JRAA5',
    branchName='develop',
    enableSoftAssert=False,
)

playwright = sync_playwright().start()
browserType = playwright.chromium
browser = browserType.launch(headless=False)
page = browser.newPage()
page.goto('https://www.python.org/')

vrt = PlaywrightVisualRegressionTracker(config, browserType)

with vrt:
    try:
        vrt.trackPage(page, 'Home page')
    finally:
        playwright.stop()

```

**Comment by dcrowe** [comment]
Oh, whoops. I can fix that.

**Review by pashidlos — APPROVED** [review]
@dcrowe awesome job!
it works as expected
going to prepare release asap

**Comment by pashidlos** [comment]
released in `4.6.0` 

https://twitter.com/VisualReTracker/status/1331639937259745284

**Pull request merged**
