### PR TITLE
Add support for python 3.6 and 3.9

### PR DESCRIPTION
**Pull request by dcrowe**
- Adds support for python 3.6 and 3.9 to CI
- Adds support for python 3.6 to setup.py

### CODE REVIEW

**Comment by dcrowe** [comment]
I know the support for 3.6 is pretty dirty but doing it better would require moving away from pipenv which is a fair bit of effort.
This project might be good way to go in future; it uses tox and separate requirements files for each python version: https://github.com/adamchainz/time-machine/tree/master/requirements

**Comment by dcrowe** [comment]
Resolves issue #9

**Comment by pashidlos** [comment]
Looks awesome for me!
thank you for contribution!

**Review by pashidlos — COMMENTED** [review]
going to merge

**Pull request merged**
